# Generated by Django 3.2.5 on 2022-01-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.TextField()),
                ('category', models.TextField()),
                ('detailedCategory', models.TextField()),
                ('intents', models.TextField()),
                ('intentNumber', models.IntegerField()),
                ('answer', models.TextField()),
            ],
            options={
                'db_table': 'chatbot',
            },
        ),
    ]
