# Generated by Django 3.2.5 on 2022-01-04 03:29

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0001_initial'),
        ('jeju_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JejuScheduleDetail',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('reg_date', models.DateField()),
                ('startday', models.DateField()),
                ('endday', models.DateField()),
                ('day', models.IntegerField()),
                ('startloc', models.TextField()),
                ('people', models.IntegerField()),
                ('relationship', models.TextField()),
                ('plane', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, size=5)),
                ('plane_detail', models.JSONField(blank=True, null=True)),
                ('acc_detail', models.JSONField(blank=True, null=True)),
                ('activity', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=50)),
                ('activity_name', django_mysql.models.ListTextField(models.CharField(max_length=255), null=True, size=50)),
                ('olle', django_mysql.models.ListTextField(models.CharField(max_length=255), null=True, size=50)),
                ('restaurant', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=100)),
                ('tourism', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=100)),
                ('shop', django_mysql.models.ListCharField(models.IntegerField(), max_length=100, null=True, size=50)),
                ('schedule', models.JSONField(blank=True, null=True)),
                ('dday', models.TextField()),
                ('acc', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='jeju_data.accommodation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.category')),
            ],
            options={
                'db_table': 'jeju_schedule_detail',
            },
        ),
    ]
